### ISSUE TITLE
Support of cardano-rosetta for Cardano 8.0.0

### ISSUE THREAD

**Issue by mbratfisch-bc** [cardano-foundation/cardano-rosetta#531]
### Ask a question

When are you going to release a new cardano-rosetta with cardano 8.0.0?

**Comment by Kammerlo** [comment]
Sorry for the delay in communication. We just merged a version bump for node 8.1.2 and preparing the new release for 2.2.0, which will include it. 
So I'm closing this issue, I hope it will solve your problems. If not let me know.
