### ISSUE TITLE
Unable to get cardano-rosetta working

### ISSUE THREAD

**Issue by liv-io** [cardano-foundation/cardano-rosetta#539]
### Ask a question

I am trying to build my own OCI container with `cardano-rosetta`.  While doing so I am facing a couple of issues and would appreciate your help.

**Issues**

 - `cardano-rosetta-server` exists without an error message when running `node index.js`
 - Node.js version 14 seems EoL and not really available anymore
 - `cardano-node` and `cardano-cli` in version 1.35.5 is not really available anymore

**Questions**

- Does `cardano-rosetta-server` work with Node.js version 18 or 20?
- Does `cardano-rosetta-server` work with cardano-node/cli version 1.35.5?
- How can I get an error message from Node.js? Increasing the `LOGGER_LEVEL` to `trace` did not help.

Please let me know if you need any details on my setup/configuration.

Any help is highly appreciated.

**Comment by liv-io** [comment]
I took a moment to build the container with Node.js version `14`.

The underlying stack is:
 - cardano-node 1.35.7
 - postgresql 15.3
 - cardano-db-sync 13.1.1.3
 - cardano-rosetta 2.1.0

The result is the same, running `cardano-rosetta-server` doesn't work for me, but maybe using a wrong command.

```
node /usr/local/src/cardano-rosetta/dist/src/server/index.js
```

I get the error message:
```
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:1074:7)
    at Object.<anonymous> (/usr/local/src/cardano-rosetta/dist/src/server/index.js:37:69)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Any inputs are appreciated.

**Comment by Kammerlo** [comment]
Hi,
we just merged a Pullrequest with a version bump for cardano-node 8.1.2 and nodejs 18. I hope it solves your problems. If not let me know.

**Comment by liv-io** [comment]
Hi @Kammerlo 
Many thanks for your efforts. I will try to look into this in the next 2 days and send you a feedback.

**Comment by liv-io** [comment]
Closing ticket as per our discussion.
