### ISSUE TITLE
README typo: Wrong docker build url

### ISSUE THREAD

**Issue by HackZhong** [cardano-foundation/cardano-rosetta#560]
### Summary

DOCKER_BUILDKIT=1 \
docker build \
  --build-arg BUILDKIT_INLINE_CACHE=1 \
  --cache-from=cardanofoundation/cardano-rosetta:master \
  -t cardanofoundation/cardano-rosetta:2.2.5 \
  .
  
  should be 
  -t **cardano-foundation/cardano-rosetta:2.2.5**

### Steps to reproduce the bug

docker build

### Actual Result

  ERROR [internal] load git source https://github.com/cardanofoundation/cardano-rosetta.git#2.2.5

### Expected Result

build finished

### Environment

1.7.0

### Platform

- [X] Linux (Ubuntu)
- [ ] Linux (Other)
- [ ] macOS
- [ ] Windows

### Platform version

Ubuntu 20

**Comment by Kammerlo** [comment]
Hi @HackZhong Thanks for reading the documentation thoroughly! 
The docker hub repository from the Cardano Foundation is called [cardanofoundation](https://hub.docker.com/repository/docker/cardanofoundation/cardano-rosetta/general) without the hypen.
