### ISSUE TITLE
Error while broadcasting transaction

### ISSUE THREAD

**Issue by dev-dantealighieri** [cardano-foundation/cardano-rosetta#561]
### Ask a question

I get the following error when i submit transaction, i have no idea why is this happening, what might be the reason?

```'Error: Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (AlonzoInBabbageUtxowPredFailure (ShelleyInAlonzoUtxowPredFailure (MissingVKeyWitnessesUTXOW (fromList [KeyHash "663ed2404fd357ded31b370237e37a6950bb7c9132977dbccedee908"])))),UtxowFailure (UtxoFailure (AlonzoInBabbageUtxoPredFailure (ValueNotConservedUTxO (MaryValue (Coin 46631389) (MultiAsset (fromList []))) (MaryValue (Coin 10000000) (MultiAsset (fromList []))))))])'```

**Comment by Kammerlo** [comment]
Hi,
it seems that a witness is missing in your transaction. Are you signing them with all needed keys? 
What Library are you using for building/signing the transaction?

**Comment by HeinrichApfelmus** [comment]
The error message indicates that the transaction that you have submitted is incomplete:

* There are missing signatures for some inputs (`MissingVKeyWitnessesUTXOW`).
* Money is not conserved: The total amount of money in the inputs does not match with the total amount of money in the outputs.

**Comment by dev-dantealighieri** [comment]
thanks!
