### ISSUE TITLE
deserialization

### ISSUE THREAD

**Issue by dev-dantealighieri** [cardano-foundation/cardano-rosetta#566]
### Ask a question

im trying to run the code down below and deserialize a signed transaction on my local machine, but i get the following error

```"Deserialization failed in Transaction.body.TransactionBody because: Invalid cbor: not the right type, expected `Map' byte received `Text'."```

i build the transaction using your repository, but cannot deserialize it locally, how to fix this?

this is important, i wish to hear from you immediately! 

thanks, dante

```ts
  getHashOfSignedTransaction(logger, signedTransaction) {
    return usingAutoFree(scope => {
      try {
        logger.info(`[getHashOfSignedTransaction] About to hash signed transaction ${signedTransaction}`);
        const signedTransactionBytes = Buffer.from(signedTransaction, 'hex');
        logger.info('[getHashOfSignedTransaction] About to parse transaction from signed transaction bytes');
        const parsed = scope.manage(CardanoWasm.Transaction.from_bytes(signedTransactionBytes));
        logger.info('[getHashOfSignedTransaction] Returning transaction hash');
        const body = scope.manage(parsed.body());
        const hashBuffer = parsed && body && Buffer.from(scope.manage(CardanoWasm.hash_transaction(body)).to_bytes());
        return hexFormatter(hashBuffer);
      } catch (error) {
        logger.error({ error }, '[getHashOfSignedTransaction] There was an error parsing signed transaction');
        throw ErrorFactory.parseSignedTransactionError();
      }
    });
  },```

**Comment by dev-dantealighieri** [comment]
@rhyslbw @AlanVerbner @t-dallas @jvieiro @Kammerlo @tomasBustamante @lgobbi-atix @catch-21 @abarretoatix  @dermetfan 

can you help, asap!

**Comment by Godspeed-exe** [comment]
Hello @dev-dantealighieri 

I believe you have opened a similar issue [here](https://github.com/cardano-foundation/cardano-rosetta/issues/565) ? 
I also believe I commented on this [here](https://github.com/cardano-foundation/cardano-rosetta/issues/565#issuecomment-2227973346)

Is this the same issue (it sounds like it)?

**Comment by dev-dantealighieri** [comment]
oh i didn't see your response, actually today i solved the issue reading the rosetta source code, thanks anyway!

im leaving how i solved it in case anyone needs it, have a nice day!

```ts
...
  const [decodedAll] = cbor.decodeAllSync(signedTransaction);
  const [decoded, extraData] = decodedAll;

  const buff = Buffer.from(decoded, 'hex');

  try {
    const tx = CardanoWasm.Transaction.from_bytes(buff);
    const txBody = tx.body();
    const txHash = CardanoWasm.hash_transaction(txBody);
    const parsed = tx.to_js_value();

    return {
      transactionHash: txHash.to_hex(),
      deserInput: parsed.body.inputs,
      deserOutputs: parsed.body.outputs,
      fee: parsed.body.fee,
      isValid: parsed.is_valid,
    };
...
}```
