### ISSUE TITLE
How to check current staking reward of account

### ISSUE THREAD

**Issue by dev-dantealighieri** [cardano-foundation/cardano-rosetta#567]
### Ask a question

hi, how can i check current staking award of an staking account?

and how can i get staking address of an account using original account or public key of it?

thanks, dante

**Comment by Kammerlo** [comment]
Hi,
within the docs it's explained how to derive your reward address, it's explained in detail here: [Link](https://github.com/cardano-foundation/cardano-rosetta/blob/master/docs/rosetta-custom-definitions.md)
You can then use the reward address and get the account balance, this will include the rewards. 

If not or if there are any other issues, let me know.

**Comment by dev-dantealighieri** [comment]
thanks!
